sudo docker stop rs1_srv1
sudo docker stop rs1_srv2
sudo docker stop rs1_srv3
sudo docker stop rs2_srv1
sudo docker stop rs2_srv2
sudo docker stop rs2_srv3
sudo docker stop cfg1
sudo docker stop cfg2
sudo docker stop cfg3
sudo docker rm cfg1
sudo docker rm cfg2
sudo docker rm cfg3
sudo docker rm rs1_srv1
sudo docker rm rs1_srv2
sudo docker rm rs1_srv3
sudo docker rm rs2_srv1
sudo docker rm rs2_srv2
sudo docker rm rs2_srv3
sudo docker stop mongos1
sudo docker rm mongos1
